### ISSUE TITLE
Add Film Availability Tracking

### ISSUE THREAD

**Issue by nonmodernist** [nonmodernist/holreg#10]
Estimated Time: 12-18 hours

## Description
Create a comprehensive system for tracking and displaying where users can actually watch these regionalist film adaptations, with automated checking where possible and manual verification for accuracy.

## Acceptance Criteria

- [ ] Internet Archive integration to check film availability
- [ ]  DVD/Blu-ray source tracking with purchase links
- [ ]  Streaming platform monitoring (when applicable)
- [ ]  Archive access information for researchers
- [ ]  Automated availability checking where possible
- [ ]  Manual verification system for accuracy
- [ ]  User-friendly availability displays across the site

## Internet Archive Integration

Features to implement:

- [ ] API integration to check if films exist on Internet Archive
- [ ]  Direct embedding of IA player where appropriate
- [ ]  Download link generation for available films
- [ ]  Automatic status updates when films become available

```javascript
// Example IA API integration
async function checkInternetArchive(filmTitle, year) {
    const searchUrl = `https://archive.org/advancedsearch.php?q=title:(${filmTitle})%20AND%20year:(${year})&output=json`;
    const response = await fetch(searchUrl);
    const data = await response.json();
    return data.response.docs;
}
```

### Sources to track:

- Warner Archive Collection - Many classic Hollywood films
- Universal Vault Series - Silent and early sound films
- Criterion Collection - Art house and important films
- Kino Lorber - Silent film specialists
- Alpha Video - Public domain releases
- Independent labels - Regional or specialized releases

### Information to capture:

- Release date and format (DVD/Blu-ray)
- Publisher/distributor
- Special features included
- Current availability status
- Purchase links (Amazon, direct from publisher)

### Streaming Platform Monitoring
Platforms to check:

- Netflix, Amazon Prime, Hulu (mainstream)
- Kanopy, Hoopla (library services)
- FilmStruck/Criterion Channel (when applicable)
- Tubi, YouTube (free with ads)
- Specialized academic platforms

### Major film archives to document:

- Library of Congress - Motion Picture Reading Room
- UCLA Film Archive - Research access procedures
- George Eastman Museum - Rochester, NY
- Academy Film Archive - Los Angeles
- Museum of Modern Art - New York
- International archives - For films held overseas

### Information to provide:

- Contact information for research requests
- Access procedures and requirements
- Researcher fees and timelines
- Viewing conditions (projection vs. digital)

## Automated Checking System

```toml
# Film metadata with availability tracking
[extra.availability_tracking]
last_checked = "2025-01-15"
internet_archive_id = "freckles1917_202501"
dvd_sources = [
    {title = "Silent Classics Collection", publisher = "Kino", status = "available"},
]
streaming_sources = [
    {platform = "Kanopy", status = "available", last_verified = "2025-01-10"},
]
archive_access = [
    {institution = "UCLA Film Archive", access_type = "researcher", contact = "..."},
]
```

### Availability Dashboard:

- "🎬 Watch Now" buttons for immediately available films
- "📀 Buy on DVD" links with pricing
- "🏛️ Archive Access" with researcher information
- "❌ Not Available" with alternative suggestions

### Filtering Options:

- "Show only films I can watch right now"
- "Show films available for purchase"
- "Show films requiring archive access"

## Files to Create/Modify

- [ ] static/availability-checker.js - Automated checking system
- [ ] templates/page.html - Enhanced availability display
- [ ] data/availability-sources.toml - Master list of sources
- [ ] static/style.css - Availability UI styling

## Maintenance System

-  Monthly automated checks for Internet Archive
-  Quarterly manual verification of DVD availability
-  Annual archive contact information updates
-  User reporting system for broken/outdated links

## Definition of Done

- Users can quickly determine how to watch any film in the collection
- Availability information is current and accurate
- Integration with existing film metadata works seamlessly
- Researchers have clear paths to access materials
- System can scale to handle 100+ films efficiently
