### ISSUE TITLE
Migrate and Enhance All Author Profiles

### ISSUE THREAD

**Issue by nonmodernist** [nonmodernist/holreg#7]
Estimated Time: 15-20 hours

## Description
Migrate existing author profiles from previous site and significantly enhance them with filmography sections, archival information, and availability tracking using the new author template structure.

### Priority Authors (complete profiles required):

- [ ] Gene Stratton-Porter (21+ film adaptations)
- [ ] Alice Hegan Rice (9 adaptations)
- [ ] Fannie Hurst (10+ adaptations)
- [ ] Edna Ferber (8 adaptations)
- [ ] Harriet Beecher Stowe (8 adaptations)

### Secondary Authors (basic profiles):

- [ ] Margaret Mitchell
- [ ] Grace Miller White
- [ ] Kate Douglas Wigginr
- [ ] [Additional authors as identified in research]

## Acceptance Criteria

- [ ]  All existing author content migrated from previous site
- [ ]  Enhanced with comprehensive filmography sections using new metadata
- [ ]  Added archival collections information for research purposes
- [ ]  DVD/streaming availability information included
- [ ]  Film availability indicators implemented (available/restricted/unavailable)
- [ ]  Author portrait images added where available
- [ ]  Cross-linking with film entries works properly

### Filmography Section:

- Visual availability indicators (green/yellow/red system)
- Separate sections for "Extant Films" and "Lost Films"
- Detailed availability notes (Internet Archive, DVD sources, archive access)
- Film status integration with new metadata structure

## Research Resources:

- Archival collections (university libraries, special collections)
- DVD and streaming sources for available films
- Academic resources for further research

## Biographical Enhancement:

- Notable works with publication years
- Geographic locations where they lived/worked
- Professional occupations beyond writing
- Film adaptation statistics and date ranges

## Content Requirements Per Author

```toml
[extra]
# Biographical details
author_dates = "1863-1924"
birth_date = "August 17, 1863"
death_date = "December 6, 1924"
occupation = ["novelist", "photographer", "filmmaker"]
locations = ["Geneva, Indiana", "Rome City, Indiana", "Los Angeles, California"]

# Film statistics
[extra.film_stats]
total_adaptations = 22
surviving_films = 10
lost_films = 12
adaptation_span = "1917-1960"
studios = ["Paramount", "Gene Stratton-Porter Productions", "RKO"]

# Film references for filmography
[extra.film_references]
lost = ["freckles-1917", "michael-ohalloran-1923", ...]
extant = ["a-girl-of-the-limberlost-1934", "freckles-1935", ...]
```

## Research Tasks Per Author

- [ ]  Verify biographical information and dates
- [ ]  Research archival collections holding their papers
- [ ]  Identify current availability of film adaptations
- [ ]  Update adaptation counts and date ranges
- [ ]  Find appropriate author portrait images
- [ ]  Cross-reference with film entries for accuracy

## Files to Modify/Create

- [ ] Existing author profile files in content/author-profiles/
- [ ] templates/author.html (ensure all new features work)
- [ ] Add missing author profiles for newly identified writers
- [ ] Update content/author-profiles/_index.md if needed

## Integration Requirements

- [ ]  Author pages link properly to their film adaptations via taxonomy
- [ ]  Film pages link back to author profiles
- [ ]  Filmography sections reflect current film entry metadata
- [ ]  Availability indicators match film status data

## Definition of Done

- All major authors have comprehensive, enhanced profiles
- Filmography sections provide clear availability guidance for researchers
- Cross-linking between authors and films works seamlessly
- Research resources help scholars find primary materials
- Visual design is consistent and professional

Stretch Goals

- Add timeline visualization of adaptation periods
- Include author quotations about film adaptations (where available)
- Link to digitized works or manuscripts where accessible
